### ISSUE TITLE
Solution file missing

### ISSUE THREAD

**Issue by YBTopaz8** [enterace/Notebook#1]
Hi, Great work on the app.
I cloned it in order to add in a few more options, but I can't properly open because the .sln file is missing.
Could you upload it as well please?

Thanks

**Comment by IliyaBadri** [comment]
**Hello there**, Sorry for the long response time.

I made the necessary [changes](https://github.com/enterace/Notebook/pull/2#issue-2722309294) in order to solve this issue.

**Thanks for your contribution!**
I mark this issue as closed.
